### ISSUE TITLE
Information deprecated, please updated. GUIDE_LANG=Chinese

### ISSUE THREAD

**Issue by BoxDengJZ** [bitemyapp/learnhaskell#128]
The Link is deprecated, which could be linked to Mac Haskell Tool installing.

Source: 

https://github.com/bitemyapp/learnhaskell/blob/master/guide-zh_CN.md

<img width="1137" alt="image" src="https://user-images.githubusercontent.com/32190193/38079741-3dcf84a2-3372-11e8-8ee6-5f6c45ca5a83.png">

It should be replaced with https://www.haskell.org/downloads

**Comment by imba-tjd** [comment]
Can be closed. This section doesn't exist anymore.
