### ISSUE TITLE
Monad transformer step by step link is outdated

### ISSUE THREAD

**Issue by akshatdevp** [bitemyapp/learnhaskell#154]
https://page.mi.fu-berlin.de/scravy/realworldhaskell/materialien/monad-transformers-step-by-step.pdf 
This link doesn't work.

**Comment by ibnuda** [comment]
http://web.archive.org/web/20200709185916/https://page.mi.fu-berlin.de/scravy/realworldhaskell/materialien/monad-transformers-step-by-step.pdf
