### ISSUE TITLE
CIS194's online edition 404 NOT Found now

### ISSUE THREAD

**Issue by WendaoLee** [bitemyapp/learnhaskell#158]
The link of [https://www.seas.upenn.edu/~cis194/spring13/lectures.html](https://www.seas.upenn.edu/~cis194/spring13/lectures.html) is missing.
I'm sorry I don't find the lawfal-published online edition of CIS194,so I just open this issue to remind.
Do hope someone can find the lawfal edition and update the README,I'm really enjoy this lecture. :)

**Comment by WendaoLee** [comment]
Oh,I find its backup in [Wayback Machine](http://web.archive.org/web/20220620044328/https://www.seas.upenn.edu/~cis194/spring13/lectures.html).
If someone is learning Haskell with this lecture,you can refer to it.

**Comment by muzimuzhi** [comment]
https://www.seas.upenn.edu/~cis1940/spring13/lectures.html works.

Upenn has recently updated their course numbering from 3-digit to 4-digit, and CIS 1940 is the new numbering for CIS 194, see https://catalog.upenn.edu/courses/cis/.
