### ISSUE TITLE
The Russian translation

### ISSUE THREAD

**Issue by Floataqq** [bitemyapp/learnhaskell#163]
Hello! I'm a Russian native speaker, and the Russian version looks like it has been google translated. May i provide a translation for it? I'm a bit bored right now and want to contribute.

**Comment by saydemr** [comment]
For sure! Just update [guide-ru.md](https://github.com/bitemyapp/learnhaskell/blob/master/guide-ru.md) and open a pull request.

**Comment by Floataqq** [comment]
I'll start working on it. Also, there seems to be an outdated version in
Russian, so i will just re-translate the English version that's currently
in the repo from scratch

вс, 24 сент. 2023 г. в 18:38, Abdullah ***@***.***>:

**Comment by Floataqq** [comment]
I opened the pull request
