### ISSUE TITLE
Add a small list of projects to explore

### ISSUE THREAD

**Issue by honza** [bitemyapp/learnhaskell#20]
I find that many Haskell tutorials and articles focus on solving a particular issue *the Haskell way*. This is great and teaches you the idiomatic way of doing things. What seems to be missing though is how you should go about structuring your app and what the ordinary ways of writing software are.

I think there is value in adding a small of projects that live on GitHub that people go into and read in a single sitting to learn how real-world Haskell feels. For example, it wasn't until way into my learning of Haskell that I learned that one shouldn't be using the `String` type for reading files and that `ByteString` is much more appropriate.

What do you think?

**Comment by sumitsahrawat** [comment]
@bitemyapp I found a lot of code examples sorted accodringly to complexity [here](https://github.com/sheganinans/pres).

**Comment by bitemyapp** [comment]
@sumitsahrawat This was one of the libraries in the "beginner" section of code examples:

https://github.com/ekmett/tables/blob/master/src/Data/Table.hs#L1-L19

I'm not sure I trust their categorization.

**Comment by sumitsahrawat** [comment]
They started learning with extensions it seems. Which surely is the opposite direction.
