### ISSUE TITLE
cs240h - 404s

### ISSUE THREAD

**Issue by cjmazey** [bitemyapp/learnhaskell#48]
Just wondering if these exist anywhere:

http://www.scs.stanford.edu/14sp-cs240h/slides/parsing.html
http://www.scs.stanford.edu/14sp-cs240h/slides/parsing-slides.html
http://www.scs.stanford.edu/14sp-cs240h/slides/parsing.md

**Comment by bitemyapp** [comment]
These have been broken since they put them up, people have asked bos to fix them, nothing has happened. Fortunately, there's still good info to harvest and parsing you can get from cis194.

**Comment by cjmazey** [comment]
Okay, thanks.  And thanks very much for the guide!

**Comment by nahuel** [comment]
I found a version of `parsing.md` here: https://github.com/valyakuttan/cs240h/tree/master/notes/l12

Maybe is an older version of the file linked in the CS240h site.

Compiled `parsing.html` and `parsing-slides.html` and uploaded them to: https://github.com/nahuel/misc/tree/master/haskell/CS240h

I think the original repo is at https://github.com/bos/stanford-cs240h but is much older and this lecture is not present.
