### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by nadirs** [bitemyapp/learnhaskell#53]
Is anyone working on the italian translation? I didn't find any, so I'm starting working on it today and thought to say it here in case anyone was already working on it or wanted to participate.

**Comment by doppioslash** [comment]
I am. Started at: https://github.com/doppioslash/learnhaskell/blob/master/guide-it.md

**Comment by nadirs** [comment]
Ah, my bad, I should have looked harder. Thanks!
