### ISSUE TITLE
cis194 course is not active

### ISSUE THREAD

**Issue by rikvdkleij** [bitemyapp/learnhaskell#63]
Submitting register form gave an error. So I send e-mail to them. It seems that this course is set inactive.

**Comment by bitemyapp** [comment]
You're not supposed to register for anything.

**Comment by rikvdkleij** [comment]
okay :-)

**Comment by rikvdkleij** [comment]
Hmm, so it's not possible to check your answers?

**Comment by bitemyapp** [comment]
@rikvdkleij there's no official capacity for this. Most people ask on the IRC channel, you could search for answers as well but you should strive to avoid that.

**Comment by rikvdkleij** [comment]
Thanks for your reply.
