### ISSUE TITLE
Why not stack?

### ISSUE THREAD

**Issue by astynax** [bitemyapp/learnhaskell#87]
Hello!
I assume what [stack](https://github.com/commercialhaskell/stack) is far more simple for beginners than GHC and Cabal (even with sandboxes). Can stack be mentioned at least (in the *"Installing Haskell"* section)?

**Comment by bitemyapp** [comment]
@astynax yeah, I was waiting for it to get stable. I think it's good enough now, I'll edit this when I have time.

**Comment by astynax** [comment]
That's a great news!

**Comment by bitemyapp** [comment]
@astynax easy there killer, we'll close it when I fix it. :)

**Comment by bitemyapp** [comment]
@joelmccracken yep, thank you :)
