### ISSUE TITLE
"DO NOT INSTALL HASKELL PLATFORM"

### ISSUE THREAD

**Issue by i3games** [bitemyapp/learnhaskell#91]
I guess this is one stumbling block confusing people who get into Haskell, before they even get into Haskell. Haskell.org is the canonical source to get Haskell, offering 3 different options for the installation. A beginner has no way to understand or make an informed decision what they should do. I would say most other online sources do recommend or point to the platfom variant. 

So if you write something like this, I would recommend to drop the capital case (which sounds intimidating) and make sure to explain the reason behind the recommendation.

**Comment by bitemyapp** [comment]
@i3games https://github.com/bitemyapp/learnhaskell#why-not-platform

**Comment by i3games** [comment]
ok, makes sense.
