### ISSUE TITLE
happylearnhaskelltutorial

### ISSUE THREAD

**Issue by GetContented** [bitemyapp/learnhaskell#94]
Heya Chris,

I was wondering if you'd be able to add our http://www.happylearnhaskelltutorial.com to your various sites (including this one) because it'd be beneficial for all of us (but mostly for our respective and collective audiences). We should put a link to your book for a what's next after reading ours. I wonder if you'd consider linking to us for people who want to start light or have no money?

**Comment by bitemyapp** [comment]
@GetContented we make sure anyone that can't afford the book is able to get a copy. See this [thread](https://www.reddit.com/r/haskell/comments/40frfj/new_release_of_the_book_haskell_programming_from/) to see what I mean.

I'd rather discuss this over email, could you ping me please?

**Comment by GetContented** [comment]
Done. I used your bitemyapp address. Hope that's the right one to use. Otherwise drop us an email via the contact form on our site above.
