### ISSUE TITLE
Worth mentioning your book?

### ISSUE THREAD

**Issue by achernyak** [bitemyapp/learnhaskell#97]
@bitemyapp, I think your book in its current state covers everything you would get from these courses, and will cover even more. Would it be worth mentioning it as an option for an up to date material?

I am just asking because these courses are still written for older version of GHC and don't always work perfectly with Stack. I think your book would be a good option for someone willing to pay the money to save a lot of headache.

**Comment by bitemyapp** [comment]
I don't disagree. I hadn't yet because people gripe when I mention the book, as if it's something to be ashamed of like 1950s pregnant women expected to hide from public view.

I'll add it sometime this week before we do the next release.

**Comment by srs1978** [comment]
Since your book is mentioned now, you could close this right?

**Comment by bitemyapp** [comment]
Makes sense to me, cheers.
